### ISSUE TITLE
test methylpy failed

### ISSUE THREAD

**Issue by jmw15** [yupenghe/methylpy#10]
Hello,

I have been trying to install methylpy, but when I run the test methylpy, I get the attached error messages. I am installing on ubuntu. Any information you could provide to fix the problem would be much appreciated.

Thank you
[test_error_msg.txt](https://github.com/yupenghe/methylpy/files/1866740/test_error_msg.txt)
[test_output_msg.txt](https://github.com/yupenghe/methylpy/files/1866741/test_output_msg.txt)

**Comment by yupenghe** [comment]
Hi, if you do not need DMRfind method, I would recommend you to run methylpy directly. The error occurred because the methylpy test is kind of out of date for the current methylpy version. Based on the files you shared, you should be able to run all methylpy methods (if external programs are installed) except DMRfind. I would start with a small dataset (e.g. 1000 reads/pairs). 

For DMRfind, you got "error while loading shared libraries: libgsl.so.0...". To resolve this issue requires installing gsl library. Check [here](https://github.com/yupenghe/methylpy#optional-step---compile-rmscpp) for details. 

Yupeng
