### ISSUE TITLE
PBAT alignment

### ISSUE THREAD

**Issue by Papareddy** [yupenghe/methylpy#24]
Hi Yupeng,

Sorry for bothering yet again. I noticed that PBAT alignment mode is not implemented in PairedEnd mode(at-least thats what its said in call_mc_pe.py). Is it implemented in SingleEnd mode?  I didn't find any apparent change with alignment with PBAT option set to True or False. 

Many thanks & have a good one.
Ranj

**Comment by yupenghe** [comment]
No problem. PBAT is implemented on both mode. Related change on the code (compared to no-PBAT) are minor because processing PBAT is not very different from typical WGBS. PBAT sequences the opposite strand compared to typical WGBD. The difference in processing is either swapping read1 and read2 (PE) or reverse complement the read (SE).

**Comment by Papareddy** [comment]
Ahh okay, mapping rate havent changed much in either modes. Many thanks, Ranj

**Comment by yupenghe** [comment]
Do you know if the library is directional or non-directional? Based on your description, it seems that the library is non-directional, which methylpy does not have support yet.

**Comment by Papareddy** [comment]
My libraries are non-direction. And yeah I realise that I only get half of the valid the alignment with methylpy. I like methylpy pipeline for plenty of  reasons.It would be awesome at some point if you can incorporate non directional alignment mode as well.

Cheers,
Ranj
