### ISSUE TITLE
DMRfind - Histogram FDR correction did not converge

### ISSUE THREAD

**Issue by connorrogerson** [yupenghe/methylpy#58]
I'm trying to run DMRfind on my PBAT data (in triplicate). DMRfind passed when testing methylpy and runs without any errors. The results aren't empty but only have one region and it's a single differentially methylated site. When eyeballing the bigwigs from the data I can clearly see regions of increased and decreased methylation, so I'm not sure why DMRfind isn't picking it them up. In the output log file I get "Histogram FDR correction did not converge. Using the smallest p-value 0.0003333333333333333 as cutoff." So I assume this cutoff is the reason I don't get many results. Is there a way to override this?

**Comment by yupenghe** [comment]
Hey, the warning is usually associated with lack of evident methylation difference. It could be that the samples are similar or the coverage is not sufficiently deep to call difference. In your case, the smallest p-value gives only one DMR, which also supports this conclusion. 

Yes, it is possible to manually parse the `rms_results.tsv.gz` file and apply a chosen p-value cutoff to get the DMRs. I would not recommend that because it may lead to a lot of false positives. An alternative is to merge all three replicates and compare the two (or more) merged samples against each other. Hope this would help.

Yupeng
